spring.application.name=qalqonAI

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/legaltech_db
spring.datasource.username=giybat_user
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.serialization.write-dates-as-timestamps=false

# Mail
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=sardorbek.uktamov.1@mail.ru
spring.mail.password=eu7fX23a1F9eFrGCywNG
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server
server.port=8080
server.domain=http://localhost:8080

# JWT
jwt.secret-key=veryLongSecretmazgillattayevlasharaaxmojonjinnijonsurbetbekkiydirhonuxlatdibekloxovdangasabekochkozjonduxovmashaynikmaydagapchishularnioqiganbolsangizgapyoqaniqsizmazgi
jwt.expiration=86400000

# Attach (file upload)
attach.upload.folder=uploads
attach.upload.url=http://localhost:8080/api/v1/attach

#########################
#       SMS SENDING (ESKIZ.UZ)
#########################
eskiz.url=https://notify.eskiz.uz/api
eskiz.login=sardorbek.uktamov.1@mail.ru
eskiz.password=EJyP6OtVcKyjfmdYm7R8CdSnXEnAhAxuxrJ0nYiH

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Logging
logging.level.api.ailawyer.uz=DEBUG
logging.level.org.hibernate.SQL=DEBUG
